spring:
  application:
    name: bank-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/migration/db.changelog.xml

server:
  port: 8081

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 1440 # 1440 = 24 часа
  admin_jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIGRldGFpbHMiLCJ1c2VybmFtZSI6IkFkbWluIiwicGFzc3dvcmQiOiJBZG1pbiIsImlkIjoxNCwiUk9MRSI6IkFETUlOIiwiaWF0IjoxNzU0Mzg3ODA3LCJpc3MiOiJUT0RPIiwiZXhwIjoxNzYwMzg3ODA3fQ.GmRqht3E2kfooHYG7dOwi5vMkEmvzGqJygLjMiQPQsc


aes:
  key: 0VyJ5vVT+08ncOkTnmQEGDBuBd2ZexzOaKNQ6N5RR8M=

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

